name: athan_app
description: "A prayer reminder"
publish_to: "none"
version: 0.4.0

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^1.2.1
  google_fonts: ^6.2.1
  intl: ^0.19.0
  cupertino_icons: ^1.0.8
  shimmer: ^3.0.0
  flutter_local_notifications: ^17.1.1
  flutter_timezone: ^1.0.8
  timezone: ^0.9.3
  liquid_pull_to_refresh: ^3.0.1
  geolocator: ^11.0.0
  geocoding: ^3.0.0
  carousel_slider: ^4.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  provider: ^6.1.2
  connectivity_plus: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: "^0.13.1"
  hive_generator: ^2.0.0
  build_runner: ^2.3.3

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icons/icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/icons/icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icons/icon.png"

flutter:
  uses-material-design: true

  assets:
    - "assets/sounds/notification.mp3"
    - assets/images/
